/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

// The `cloudflare:workers` virtual module types (env, getRequestContext, etc.)
// are generated by `npx wrangler types` into `worker-configuration.d.ts`.

declare namespace App {
  interface Locals {
    cfContext: import('@astrojs/cloudflare').Runtime['cfContext'];
  }
}
